application: svghanzi
version: 0-2-test
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: README.html
  upload: README.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
    
- url: /.+
  script: zaoziweb.application